from .grid_detector_block import GridDetectorBlock
from .map_detector_block import MapDetectorBlock
from .calculation_data_block import CalculationDataBlock
from .dictor_settings_block import DictorSettingsBlock
from .general_settings_block import GeneralSettingsBlock
from .elevation_detector_block import ElevationDetectorBlock